#!/bin/bash
#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2021 Frédéric Pierret (fepitre) <frederic@invisiblethingslab.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

set -e
set -o pipefail

if [ "${DEBUG}" == 1 ]; then
    set -x
fi

if test $# -ne 2; then
	echo "Please provide spec file and dist tag to query."
	exit 1
fi

SPEC_FILE="$1"
DIST_TAG="$2"

version_release_arch="$(rpmspec --srpm --define "dist .${DIST_TAG}" -q --qf '%{version}-%{release}.%{arch}\n' "${SPEC_FILE}")"

# Get builtrpms from rpmspec without debuginfo
# see https://github.com/rpm-software-management/rpm/issues/1878
readarray -t packages < <(rpmspec --define "dist .${DIST_TAG}" --nodebuginfo -q --qf '%{name}\n' --builtrpms "${SPEC_FILE}")

builtrpms=()
for pkg in ${packages[*]}
do
    builtrpms+=("${pkg}-${version_release_arch}.rpm")
    if [ "${pkg%%-devel}" == "${pkg}" ]; then
        builtrpms+=("${pkg}-debuginfo-${version_release_arch}.rpm" "${pkg}-debugsource-${version_release_arch}.rpm")
    fi
done

printf '%s\n' "${builtrpms[@]}"
