#!/bin/bash
#
# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2022 Frédéric Pierret (fepitre) <frederic@invisiblethingslab.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

# This script parses and creates a file containing package info
# necessary for the build process.

set -e
set -o pipefail

if [ "${DEBUG}" == 1 ]; then
    set -x
fi

if test $# -ne 2; then
	echo "Usage: source_dir debian_directory"
	exit 1
fi

SOURCE_DIR="$1"
DEBIAN_DIRECTORY="$2"

DIRECTORY_BN="$(basename "$DEBIAN_DIRECTORY")"

SCRIPTS_DIR="$(dirname "$0")"

"${SCRIPTS_DIR}"/debian-parser changelog --package-release-name \
    "${SOURCE_DIR}/${DIRECTORY_BN}/changelog" \
    > "${SOURCE_DIR}/${DIRECTORY_BN}_package_release_name"

"${SCRIPTS_DIR}"/debian-parser changelog --package-release-name-full \
    "${SOURCE_DIR}/${DIRECTORY_BN}/changelog" \
    >> "${SOURCE_DIR}/${DIRECTORY_BN}_package_release_name"

grep -Po "(?<=^3.0 \()\w+" < "${SOURCE_DIR}/${DIRECTORY_BN}/source/format" \
    >> "${SOURCE_DIR}/${DIRECTORY_BN}_package_release_name"
