#!/bin/bash

# Script called by qubesbuilder.ProcessGithubCommand for handling "Build-template"
# command
#
# First argument is expected to be a command file path, already
# verified against trusted keys set.
# Second argument is a key fingerprint used to sign the command

if [ $# -lt 2 ]; then
    echo "Usage: $0 <command-file> <key-fingerprint>" >&2
    exit 1
fi

if [ "$DEBUG" == "1" ]; then
    set -x
fi

command_file="$1"
signer_fpr="$2"

scripts_dir="/usr/local/lib/qubes-builder-github"

# shellcheck source=qubesbuilder/plugins/github/lib/functions.sh
. "$scripts_dir/lib/functions.sh"

read -r action release_name dist timestamp < "$command_file"

if [ "x$action" != "xBuild-template" ]; then
    echo "Invalid action" >&2
    exit 1
fi

case "${dist}" in
    *[/.$IFS]*)
        echo "Forbidden character in dist" >&2
        exit 1
        ;;
    "")
        echo "Empty dist" >&2
        exit 1
        ;;
esac


# release_name verified in build_template_for_release function
# dist verified in build_template_for_release function

if ! printf "%s" "$timestamp" | grep -q "^[0-9]\{12\}Z$"; then
    echo "Invalid timestamp format" >&2
    exit 1
fi

timestamp_format="%Y%m%d%H%M"
timestamp_max=$(date -u -d '+5 min' +$timestamp_format)
timestamp_min=$(date -u -d '-1 hour' +$timestamp_format)
if [ "${timestamp::-1}" -gt "$timestamp_max" ] || [ "${timestamp::-1}" -lt "$timestamp_min" ]; then
    echo "Timestamp outside of allowed range" >&2
    exit 1
fi

# enable logging (use qrexec policy to redirect to the right VM)
export QUBES_BUILD_LOG_CMD="qrexec-client-vm 'dom0' qubesbuilder.BuildLog"

build_template_for_release() {
    local_config_release_name="$1"
    local_builder_dir="$2"

    if [ "$local_config_release_name" != "$release_name" ]; then
        return
    fi

    # get templates as configured in builder.yml, without resolving aliases yet
    supported_templates=$("$local_builder_dir"/qb --builder-conf "$local_builder_dir"/builder.yml config get-templates)
    allowed_templates=$(get_allowed_templates "$local_builder_dir" "$signer_fpr")

    if ! echo "$supported_templates" | grep -q "$dist"; then
        # not listed in this builder instance
        return
    fi

    if ! echo "$allowed_templates" | grep -q "$dist"; then
        # not allowed here
        return
    fi

    "$local_builder_dir/qubesbuilder/plugins/github/scripts/auto-build-template" "$local_builder_dir" "$dist" "$timestamp"
}

execute_in_each_builder build_template_for_release
