#!/bin/bash

# This is script to automate template build process in reaction to properly signed
# command.

SCRIPTS_DIR="$(dirname "$0")"

# shellcheck source=qubesbuilder/plugins/github/scripts/auto-build-functions.sh
. "$SCRIPTS_DIR/auto-build-functions.sh"

if [ "$DEBUG" == 1 ]; then
    set -x
fi

usage() {
    echo "Usage: $0 builder-dir dist timestamp" >&2
    echo "builder-dir is Qubes OS builder directory" >&2
    echo "distribution as configured in builder.yml" >&2
    echo "timestamp expected in format %Y%m%d%H%M" >&2
    echo "The repository where template is uploaded to is taken from repository-publish in builder.yml" >&2
}

if [ $# -lt 3 ]; then
    usage
    exit 1
fi

set -e

# Get builder directory from first arg and remove
# it from the other args that are passed to builder
BUILDER_DIR="$1"
shift 1

cd "$BUILDER_DIR" || {
    echo "ERROR: Invalid builder directory."
    exit 1
}

# Sanity checks
if [ "${1##*/}" != "${1}" ]; then
    echo "ERROR: Found '/' in argument" >&2
    exit 1
fi

template_dist="$1"

found=
for d in $(./qb config get-templates); do
    if [ "$d" = "$template_dist" ]; then
        found=1
    fi
done
if [ -z "$found" ]; then
    echo "ERROR: Template not enabled here: $template_dist" >&2
    exit 1
fi

export TEMPLATES="$template_dist"

if ! printf "%s" "$2" | grep -q "^[0-9]\{12\}Z$"; then
    echo "ERROR: Invalid timestamp format" >&2
    exit 1
fi
timestamp="$2"

# check if template is already built
timestamp_file="$BUILDER_DIR/artifacts/templates/build_timestamp_$template_dist"
if [ -r "$timestamp_file" ]; then
    timestamp_existing=$(cat "$timestamp_file")
    if [ "${timestamp::-1}" -lt "${timestamp_existing::-1}" ]; then
        echo "INFO: Newer template ($timestamp_existing) already built" >&2
        exit 0
    elif [ "$timestamp_existing" == "$timestamp" ]; then
        template_status=$(./qb -t "$template_dist" repository check-release-status-for-template || :)
        if [ "$template_status" != "not released" ]; then
            echo "INFO: Template already built" >&2
            exit 0
        fi
    fi
fi

repo=$(./qb config get-var repository-publish | jq -r '.templates | select( . != null )')
if [ -z "$repo" ]; then
    echo "ERROR: Default templates repository in builder.yml is not set" >&2
    exit 1
fi

# qubes-builder uses this variable (if exists) to define the build timestamp
TEMPLATE_TIMESTAMP=""
export TEMPLATE_TIMESTAMP

if ! "$SCRIPTS_DIR"/make-with-log "$BUILDER_DIR" -t "$template_dist" template prep build; then
    build_failure template vm "$template_dist" "$(get_build_log_url)"
    exit 1
fi

build_logs="linux-template-builder-vm-${template_dist}=$(get_build_log_url)"
export BUILD_LOGS_URL="$build_logs"

if ! "$SCRIPTS_DIR"/make-with-log "$BUILDER_DIR" -t "$template_dist" template sign; then
    build_failure template sign "$template_dist" "$(get_build_log_url)"
    exit 1
fi

if ! "$SCRIPTS_DIR"/make-with-log "$BUILDER_DIR" -t "$template_dist" template publish upload; then
    build_failure template upload "$template_dist" "$(get_build_log_url)"
    exit 1
fi
