#!/bin/bash

set -e
set -o pipefail

# Get builder directory from first arg and remove
# it from the other args that are passed to builder
BUILDER_DIR="$1"
shift 1

cd "$BUILDER_DIR"

if [ -z "$QUBES_BUILD_LOG_CMD" ]; then
    ./qb "$@"
    exit $?
fi

exec {real_stdout_fd}>&1

(
export LC_ALL=C.UTF-8
echo "> starting build with log"
echo ">> args: $*"
for v in COMPONENTS DISTRIBUTIONS TEMPLATES; do
    echo ">> $v=${!v}"
done
for c in $COMPONENTS; do
    echo ">> $c:"
    echo ">>   commit-hash: $(./qb -c "$c" config get-components --attribute source_commit_hash)"
    echo ">>   source-hash: $(./qb -c "$c" config get-components --attribute source_hash)"
done
echo "> running qb"
./qb "$@"
echo "> done"
) 2>&1 | tee -a /dev/fd/$real_stdout_fd | eval "$QUBES_BUILD_LOG_CMD"
